apiVersion: v1
kind: Service
metadata:
  name: dotnet-producer-service
  labels:
    app: dotnet-producer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: dotnet-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-producer-deployment
  labels:
    app: dotnet-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-producer
  template:
    metadata:
      labels:
        app: dotnet-producer
    spec:
      containers:
        - name: dotnet-producer
          image: kafka-producer-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: Kafka__BootstrapServers
              value: "kafka-service:9092"
            - name: Kafka__Topic
              value: "dotnet-topic"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-consumer-deployment
  labels:
    app: dotnet-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-consumer
  template:
    metadata:
      labels:
        app: dotnet-consumer
    spec:
      containers:
        - name: dotnet-consumer
          image: kafka-consumer-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: Kafka__BootstrapServers
              value: "kafka-service:9092"
            - name: Kafka__Topic
              value: "dotnet-topic"
